apiVersion: apps/v1
kind: Deployment  
metadata:
  name: nodeserver
  labels:
    app: nodeserver
spec: 
  selector:
    matchLabels:
      app: nodeserver
  replicas: 2
  template:
    metadata:
     labels:
      app: nodeserver
    spec:
      containers:
        - name: nodeserver
          image: "lfernandocosta/hello-node:v6.5"
          envFrom:
            - configMapRef:
                name: nodeserver-env
          volumeMounts:
            - mountPath: "/myfamily"
              name: config 
      volumes:
        - name: config
          configMap: 
            name: configmap-family 
            items:
            - key: members
              path: "family.txt"










          # env: 
          #   - name: NAME
          #     valueFrom: 
          #       configMapKeyRef:
          #         name: nodeserver-env
          #         key: NAME
                  
          #   - name: AGE
          #     valueFrom:
          #       configMapKeyRef:
          #         name: nodeserver-env
          #         key: AGE
