apiVersion: apps/v1
kind: Deployment  
metadata:
  name: nodeserver
  labels:
    app: nodeserver
spec: 
  selector:
    matchLabels:
      app: nodeserver
  replicas: 2
  template:
    metadata:
     labels:
      app: nodeserver
    spec:
      containers:
        - name: nodeserver
          image: "lfernandocosta/hello-node:v6.6"

          resources:
            requests:
              cpu: 100m
              memory: 20Mi
            limits:
              cpu: 500m 
              memory: 25Mi

          readinessProbe:
            httpGet:
              path: /healthz
              port: 3333
            periodSeconds: 3
            failureThreshold: 1
            initialDelaySeconds: 10 

          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureTreshold: 30
            
          # livenessProbe:
          #   httpGet:
          #     path: /configmap
          #     port: 3333
          #   periodSeconds: 5
          #   failureThreshold: 3
          #   timeoutSeconds: 1
          #   successThreshold: 1

          envFrom:
            - configMapRef:
                name: nodeserver-env

            - secretRef:
                name: nodeserver-secret
          volumeMounts:
            - mountPath: "/myfamily"
              name: config 
      volumes:
        - name: config
          configMap: 
            name: configmap-family 
            items:
            - key: members
              path: "family.txt"










          # env: 
          #   - name: NAME
          #     valueFrom: 
          #       configMapKeyRef:
          #         name: nodeserver-env
          #         key: NAME
                  
          #   - name: AGE
          #     valueFrom:
          #       configMapKeyRef:
          #         name: nodeserver-env
          #         key: AGE
